### ISSUE TITLE
Support only running once

### ISSUE THREAD

**Issue by chriskrycho** [elwayman02/ember-scroll-modifiers#241]
It's fairly common to want to run a callback the *first* time an item becomes visible, and not again after that. We could perhaps support something like `once=true` as an argument here. Very open to design discussion around the right way to do this, though; the caller can also simply cache a value (which is what I'm going to do to work around the absence of this for now).

**Comment by elwayman02** [comment]
I'm open to adding an optional param for that! `once` is an ok name for it, will think on it to see if something better comes up.

**Comment by elwayman02** [comment]
Alternatively, should this just be a separate modifier that extends from `did-intersect`? If an item starts visible and never intersects with the container, `did-intersect` will never fire. However, we could build a modifier that checks visibility of the element at init and then utilizes intersection detection after that and unregisters the observer after the first event. What do you think?

**Comment by ygongdev** [comment]
```If an item starts visible and never intersects with the container, did-intersect will never fire```
I actually think `did-intersect` will fire for this case because technically you're already intersecting with the viewport. I think this is because how we determine an `intersection` atm is defined as when the element is visible within the viewport.
If this is not the intended behavior, then we should probably look into refactoring it.

Also another idea is that I think it would be great if this modifier can be used to implemented a modifier-version of [spaniel](https://github.com/linkedin/spaniel), which _might_ require more closer-to-the-metal customization(s) than  what our `enter` and `exit` callback hooks can support.

**Comment by elwayman02** [comment]
Actually, I think you're right that it does fire an initial event if visible. We should test this by rendering something outside the viewport and ensure it doesn't also fire an event, though.

I 100% believe that this project can be the basis for a modifier version of spaniel, yes. That is one of the things I had in mind when I created it. :)

**Comment by elwayman02** [comment]
@chriskrycho do you think it would make more sense to define this as a number, rather than a boolean? That is - a parameter that says "fire the first X events that occur", where your use case would define X as 1? By default the value would be undefined and the modifier would ignore that behavior. Otherwise, it would count each event fired until it reaches the supplied value and then stop firing?

This is obviously more flexible, but I'm wondering if this is over-complicating the solution. Do we think there's a reasonable chance that people would want to build something where X>1 but isn't unlimited?

**Comment by chriskrycho** [comment]
I could see going either way on that consideration. 🤔 

```hbs
<div {{did-intersect onEnter=this.doSomething maxTimes=1}}>
  {{! ... }}
</div>
```

That's not bad, and I think it keeps the API simple enough. The most common use cases are handled easily enough, while supporting more if there's reason to.

**Comment by elwayman02** [comment]
Maybe `maxIntersections` is a good name for it?

**Comment by ygongdev** [comment]
>We should test this by rendering something outside the viewport and ensure it doesn't also fire an event, though.

I was able to verify this is working in the demo by pushing the intersection box out of viewport on initial view.

However, I wasn't able to find a good way to write a test for this because that would require hooking into the IntersectionObserver to figure out when it is firing since our `addEnterCallback` and `addExitCallback` will be fired for setup when initialized even when it isn't in view.

**Comment by elwayman02** [comment]
That's fine. I was mostly just wanting to make sure we knew *why* that first event was firing. A smoke test satisfies me, thanks!

**Comment by ygongdev** [comment]
> Maybe `maxIntersections` is a good name for it?

I think we should have 2 `maxIntersections`, one to track `enter` and another to track `exit`. It is possible that some users also care about the number of exit as well?

**Comment by elwayman02** [comment]
Good point. How about `maxEnter` and `maxExit`?

**Comment by ygongdev** [comment]
Yeah that sounds fine, I can work on an experimental PR meanwhile.
