### ISSUE TITLE
[did-intersect] Export addon-test-support helpers 

### ISSUE THREAD

**Issue by ygongdev** [elwayman02/ember-scroll-modifiers#243]
The async nature of `Intersection Observer` makes it hard to test deterministically in the Ember ecosystem.

We should implement a set of helpers around a deterministic `Intersection observer` mock and export them for the consumers to use.

**Comment by elwayman02** [comment]
I don't entirely agree with this. Consumers should not even have to know that this project uses `IntersectionObserver` under the hood. Why would they care? All they care about is, does this modifier fire events when an intersection occurs? The only thing they should worry about mocking is the ability to deterministically fire events. To that end, maybe there are helpers we could export to make this easier, but I don't think mocking `IntersectionObserver` is the right level of granularity. That forces the consumer to assume too much about the internal workings of the modifier itself, when all they should care about is being able to trigger the external API of the modifier.

**Comment by ygongdev** [comment]
> The only thing they should worry about mocking is the ability to deterministically fire events

Yeah this is the only thing we should care about.  I was unsure on how we can accomplish this without mocking the `IntersectionObserver` internally. We definitely don't have to export our internal `IntersectionObserver` mock, if that was what it sounded like haha.

**Comment by elwayman02** [comment]
For our own internal testing, mocking `intersection-observer-admin` is the correct approach, since that is our external dependency. For external testing, the correct approach is to mock the modifier itself. Now, we may be able to come up with a clever way to do that mocking via a helper that makes it very easy to programmatically trigger the modifier's expected behaviors. That's where the value will come from.
