### ISSUE TITLE
Update to/support Ember v5

### ISSUE THREAD

**Issue by boris-petrov** [elwayman02/ember-scroll-modifiers#850]
Ember v5 is out! :) It would be nice to update to it and/or add support for it in [peerDependencies](https://github.com/elwayman02/ember-scroll-modifiers/blob/v6.0.0/package.json#L88).

**Comment by elwayman02** [comment]
I agree! I'm not sure when exactly I'll have time to look at this, but I'd be happy to accept a PR. It might be as simple as updating peerDependencies for the short-term, since the ember-try scenarios will automatically check the latest release. There's a small possibility that Ember 5 will break the field-guide demo app, but as long as ember-modifier v4 supports Ember 5, then I don't think any of the code shipped to consumers should break.

**Comment by elwayman02** [comment]
Released as v7.

Further Ember 5 support in the demo is blocked on #854, but should not impact consumers (tests are passing).

**Comment by boris-petrov** [comment]
Thanks! I don't think a major version was needed but no matter, thank you for the release! :)

**Comment by elwayman02** [comment]
It was a major version because I also dropped Ember 3.28 and Node 14 support.
